### ISSUE TITLE
Opennos TODO ?? probably useful

### ISSUE THREAD

**Issue by WallcroftUK** [WallcroftUK/Noskito#5]
- [ ] Loginserver Architecture
- [ ] Logging
- [ ] Networking
- [ ] DAO
- [ ] Packet Factory / Management
- [ ] Channel / Server Management
- [ ] Account Management
- [ ] Character Management
- [ ] Keep Alive
- [ ] Map
- [ ] Movement
- [ ] Grid-System (Blocking)
- [ ] Item support
- [ ] Inventory support
- [ ] Exchange support
- [ ] Upgrade support
- [ ] Equipment support
- [ ] NPC support
- [ ] Shop support
- [ ] Skill
- [ ] Monster
- [ ] Vehicle system
- [ ] Battle (excluding PvP)
- [ ] Groups
- [ ] XP
- [ ] Drop
- [ ] Skill bar
- [ ] New inventory system
- [ ] Parcel/Letter
- [ ] FriendList (Except Join Miniland, which comes later)
- [ ] Family (All the basic stuff)
- [ ] BlackList
- [ ] Multi Channel - Server support
- [ ] Bazaar
- [ ] Static Bonuses
- [ ] Pet/Partner System
- [ ] Miniland Objects
- [ ] Mini-Game
- [ ] Warehouse (Family and Private Warehouse)
- [ ] Timespaces
- [ ] Arena
- [ ] Jewelry
- [ ] Act4 + Shell
- [ ] Arena of Master/Talent(base)
- [ ] Raids
- [ ] BCard/Buff System
- [ ] Pvp
- [ ] MapInstance
- [ ] Rainbow battle
- [ ] Quest
- [ ] Full Arena of Master/Talent system
- [ ] Ice breaker
